favicon: /img/favicon.png
apple_touch_icon: /img/apple-touch-icon.png
title_join_string: ' ~ '
new_post_name: ':year-:month-:day-:title.md'

highlight:
  enable: false
post_asset_folder: true

theme: fluid
deploy:
  type: git
  repo: 'git@github.com:wangkunSE/wangkunSE.github.io.git'
  branch: hexo/blog
mouse_click:
  enable: false
  style: values
title: Soul
