# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          WK's Blog
paginate:       5
baseurl:        ""
url:            "https://wangkunSE.github.io"
repositryurl:   "https://github.com/wangkunSE/wangkunSE.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Chester How
  url:          http://chester.how
  email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
favicon: /favicon.ico
