# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          WK's Blog
paginate:       5
baseurl:        "https://github.com/wangkunSE/wangkunSE.github.io"
url:            "https://wangkunSE.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Donny Wang
  email:        wkzuilovess@gmail.com

# Custom vars
version:        3.4.1

# Gems
gems:
  - jekyll-paginate

favicon: /favicon.ico
